apiVersion: v1
kind: Service
metadata:
  name: open-shop-app-service
spec:
  type: NodePort
  selector:
    app: open-shop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Access it at http://localhost:30080

